language: java

jdk:
  - oraclejdk8

sudo: false
install: true
addons:
  sonarqube:
    organization: "vicctor-github"
    token:
      secure: "4c3be81ecbfd04c8cb547c536dd00a6b0d8f106b"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
